apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-Application
  namespace: argocd
spec:
  project: default
  
  source:
    repoURL: https://github.com/sam-side-pro/minikube-argocd-config
    TargetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespaces: myapp
  syncPolicy:
    syncOptions:
    - CreateNameSpace=true

    automated:
      selfHeal: true
      prune: true